---
language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    # - os: linux
    #   dist: xenial
    #   sudo: required
    #   python: 2.7

# Install ansible
addons:
  apt:
    update: true
    packages:
      - python-pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install ca-certificates python-urllib3 python-openssl python-pyasn1
  - sudo pip install ndg-httpsclient

install:
  # Install ansible
  - sudo pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking=False' > ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/